### ISSUE TITLE
FunctionalID is generating incorrectly.

### ISSUE THREAD

**Issue by npink42** [circles-arrows/blueprint41#11]
https://github.com/circles-arrows/blueprint41/blob/172ad5f95a097bfc65afd94b8af76a34cfd4bf24/Blueprint41/DatastoreTemplates/Domain_Data_Node.cs#L205

When I generate the model based on my dto's, it is generating all my `FunctionalId`s based on 'Invoice' instead of the underlying type name.

Using nuget version 1.0.18.

Thx!

**Comment by circles-arrows** [comment]
Should be fixed in version 1.0.19 now.

Please let us know if its not working as expected,
Thanks!

**Comment by npink42** [comment]
Still not working.  When i download 1.0.19 and pull the dll out, it still says 18. 
![image](https://user-images.githubusercontent.com/178287/132509740-968d681e-52d3-424c-8b88-33fea5cf9934.png)

**Comment by circles-arrows** [comment]
Re-released the packages, hope that it works this time around...

**Comment by npink42** [comment]
Works great.  Thx for the rapid response.  Do you put out release notes for that package?  I was trying to figure out what some of your fixes were.  It seems like transactions were ignoring readWriteMode= false.  I'm going to test the new package as it seems like you changed some of that code.

**Comment by circles-arrows** [comment]
The other thing we fixed was a bug related to time dependent relationships sometimes not saving correctly and causing a bug during save. But no, we didn't really make release notes yet. We'll think about if we can do release notes in the future.
